### ISSUE TITLE
The download link seems to be not working

### ISSUE THREAD

**Issue by YZsZY** [fraunhoferhhi/D-NeuS#6]
Hi author, the download link in Google cloud seems to be not working, can you update it or share the code for data processing?

**Comment by LiXinghui-666** [comment]
> Hi author, the download link in Google cloud seems to be not working, can you update it or share the code for data processing?

Hello, I would like to ask if you have the processed data? I see you closed the issue. I wonder if it would be convenient for you to share the data link. Thank you very much!
